server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8088
          predicates:
            - Path=/book/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: login-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

  application:
    name: BOOK-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/